### ISSUE TITLE
Css not Found 

### ISSUE THREAD

**Issue by sharmaanil8866** [mckenziearts/laravel-notify#4]
GET http://127.0.0.1:8000/vendor/mckenziearts/laravel-notify/css/notify.css net::ERR_ABORTED 404 (Not Found)
login:8 GET http://127.0.0.1:8000/vendor/mckenziearts/laravel-notify/js/notify.js net::ERR_ABORTED 404 (Not Found)

**Comment by mckenziearts** [comment]
Did you publish assets?

```php
php artisan vendor:publish --provider='Mckenziearts\Notify\LaravelNotifyServiceProvider'
```

**Comment by sharmaanil8866** [comment]
Yes I published assets

**Comment by dev-amitsolanki** [comment]
yes, after publish 
Unable to locate publishable resources.
this message is located and CSS and js are still not found.

**Comment by Hassen307** [comment]
same problem occurred here

**Comment by maggz69** [comment]
Same problem as well.

More information: Laravel 6.0

![image](https://user-images.githubusercontent.com/20341115/69592046-642c7880-0ffd-11ea-85fe-f191cfd61013.png)
![image](https://user-images.githubusercontent.com/20341115/69592092-87572800-0ffd-11ea-8ef7-a4c45b981178.png)

**Comment by mckenziearts** [comment]
Try to do only 

```php
php artisan vendor:publish
```

To get sometime like this and choose to publish notify assets by this way

<img width="649" alt="Screenshot 2019-11-26 at 05 56 32" src="https://user-images.githubusercontent.com/14105989/69600654-becfcf80-1011-11ea-9cf1-10e192f6914e.png">

**Comment by Hassen307** [comment]
@mckenziearts +1
it works fine now

**Comment by mckenziearts** [comment]
Great i will close this issue.

**Comment by EhtuCom** [comment]
> Try to do only
> 
> ```
> php artisan vendor:publish
> ```
> 
> To get sometime like this and choose to publish notify assets by this way
> 
> <img alt="Screenshot 2019-11-26 at 05 56 32" width="649" src="https://user-images.githubusercontent.com/14105989/69600654-becfcf80-1011-11ea-9cf1-10e192f6914e.png">

Great! it work!
